### ISSUE TITLE
Zellij support

### ISSUE THREAD

**Issue by notramo** [enricozb/popup.kak#2]
[Zellij](https://zellij.dev/) is `tmux` on steroids.
The plugin should autodetect if Kakoune is running inside of `tmux` or `zellij`. This can be done using the `$ZELLIJ_SESSION_NAME` variable.

From inside a `zellij` pane, the following shell command can launch a new popup pane with the process `kak`
```
 zellij run --floating -- kak
 ```

**Comment by enricozb** [comment]
I don't think this is necessary, as this plugin does not require you to run kakoune _inside_ of any terminal multiplexer. The multiplexing is done through info modals, and the state of the popup window is delegated to tmux.
